# Generated by Django 5.1.5 on 2025-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
