# Generated by Django 5.1.6 on 2025-02-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_actor_movie_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_user',
        ),
    ]
