# Generated by Django 5.1.5 on 2025-02-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_user_otp_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
